### ISSUE TITLE
repo headings only appear when github logo absent

### ISSUE THREAD

**Issue by jonorthwash** [sushain97/apertium-on-github#24]
Narrow:
![screenshot-2018-2-27 apertium source browser](https://user-images.githubusercontent.com/963849/36751513-5d36e13e-1bce-11e8-89f5-0e68b52baea6.png)

Narrower:
![screenshot-2018-2-27 apertium source browser 1](https://user-images.githubusercontent.com/963849/36751542-773106e6-1bce-11e8-9226-98caf9cce744.png)

In between, with github logo, but still with only 3 columns:
![screenshot-2018-2-27 apertium source browser 2](https://user-images.githubusercontent.com/963849/36751571-91f7c348-1bce-11e8-98dd-09157a2ee09d.png)

**Comment by sushain97** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=488725

**Comment by sushain97** [comment]
this is why I don't write CSS @shardulc

**Comment by sushain97** [comment]
😠

**Comment by jonorthwash** [comment]
Hmm, is it that they need more examples to figure out what's wrong?  Are they just ignoring the issue?  Nine years is a bit on the extreme side...

**Comment by sushain97** [comment]
I think it's just not high priority enough since the workaround is somewhat straightforward.
