### ISSUE TITLE
Amend the by-laws

### ISSUE THREAD

**Issue by shardulc** [sushain97/apertium-on-github#26]
I just created the `by-laws-amend` branch with a [`by-laws.md`](https://github.com/sushain97/apertium-on-github/blob/by-laws-amend/by-laws.md) file, unmodified from the [actual in-effect by-laws](http://wiki.apertium.org/wiki/By-laws) on the Apertium wiki. These by-laws need to be amended for two purposes:
1. The procedures, terms, etc. need to change to reflect the migration to GitHub.
1. Some items are ambiguous or unclear and need to be better worded.

Specific things to do:
- [ ] Revamp the Developers, Committers, and PMC sections to reflect the GitHub structure
    - rename: Outside Collaborators, Organization Members, Organization Owners
    - what is a 'repository'?
    - permissions and responsibilities (N.B. voting rights to Members)
    - how someone becomes a Outside Collaborator or a Organization Member
- [ ] Add the concept of 'package maintainers':
    - who they are (repository admins)
    - how they are established, disestablished, and who does their job if they don't exist
    - their permissions and responsibilities (N.B. releases)
- [ ] Add the concept of 'teams' and 'team maintainers':
    - how they are established and disestablished
    - their permissions and responsibilities
- [ ] (optional, maybe not right now) Make the election wording less ambiguous

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/organisation/pull/13
