### ISSUE TITLE
Global svn lock script

### ISSUE THREAD

**Issue by sushain97** [sushain97/apertium-on-github#27]
SF's interactive shell service is still down so we can't add a pre-commit-hook.

Instead, let's just do a recursive `svn lock`. It won't solve the problem of people adding new files/folders but it's good enough for now.

Script should look something like this:

```bash
message='Apertium has migrated to Git/GitHub. See repositories at https://apertium.github.io/apertium-on-github/source-browser.html. DO NOT USE SourceForge/SVN. This repo will be deleted.'
svn list --recursive $SVN_ROOT | xargs -n 256 -I {} svn lock --force --message $message --targets {}
```

limited to 256 per command to keep argument list from hitting limits

cc @shardulc @TinoDidriksen

**Comment by TinoDidriksen** [comment]
Yeah, that'll sadly be what we have to do.
