### ISSUE TITLE
Remember svn revision

### ISSUE THREAD

**Issue by TinoDidriksen** [sushain97/apertium-on-github#31]
https://subgit.com/remote-book.html#client_config - notes are not pushed to Github? I see the notes in the repos on the server, but I can't fetch them from Github.

**Comment by sushain97** [comment]
Might not have been pushing tags...

**Comment by sushain97** [comment]
I don't think this is worth a re-import though.

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-on-github/blob/master/util.sh#L57

**Comment by TinoDidriksen** [comment]
Sadly, push --all does not push tags. Need push --tags for that. --all is not all. Oh, and of course you can't push --all --tags; have to do it in two steps.

**Comment by sushain97** [comment]
Well, I took a look and it seems like we don't really have many if any meaningful tags in SVN. So I think that is fine for existing repos?

Regardless, for future repos the following two lines should be added and tested:
```
git push origin --tags
git push origin refs/notes/*
```

**Comment by TinoDidriksen** [comment]
I absolutely think it's worth pushing those notes (and whatever tags may exist). Just push those from the old imports.

**Comment by sushain97** [comment]
The imported bare git repos are immediately deleted after completion. Fixing this would require re-importing everything.

**Comment by sushain97** [comment]
54559e25e84c9fb009488ac237f8a3002e5aa6cd
