### ISSUE TITLE
Handle conflicting svn moves

### ISSUE THREAD

**Issue by TinoDidriksen** [sushain97/apertium-on-github#33]
The core tools and some repos have been moved/copied/mangled in ways that defy git-svn and SubGit.

Need a script to separately convert and merge the histories of such repos - something scripted around `svn log`.

- [x] lttoolbox
- [x] apertium
- [x] apertium-lex-tools
- [x] apertium-separable
- [x] es-de/spa-deu
- [x] es-an/spa-arg
- [x] es-ca/spa-cat
- [x] fr-ca/fra-cat
- [x] en-ca/eng-cat
- [ ] es-it
- [ ] tur-kir

**Comment by sushain97** [comment]
Also for
- [ ] en-ca/eng-cat
- [ ] es-de
- [ ] es-an
- [ ] es-ca/spa-cat
- [ ] fr-ca/fra-cat
- [ ] es-it
- [ ] tur-kir

**Comment by jimregan** [comment]
This is bringing back all kinds of horrible memories—anything that's really old (apertium, lttoolbox, apertium-es-ca, apertium-es-pt, etc.) was originally on top level directory. incubator was originally toplevel, then went to branches, then back again. There was an incident with a gsoc candidate who accidentally deleted everything but the module he was working on, and sourceforge was flaky about 'svn mv' for a long time and would often just 'rm', and there were a few times when people used 'svn mv' to releases/ instead of 'svn cp'

**Comment by TinoDidriksen** [comment]
Sure, and it's all manageable. It'll take some forensics and time, but it's a one-time task. It will rewrite the history for the affected repos. No pull requests, no merges, no branches.

**Comment by jonorthwash** [comment]
- [ ] tur-kir - seems to be missing all history before [this commit](https://sourceforge.net/p/apertium/svn/48431/log/?path=/nursery/apertium-tur-kir/apertium-tur-kir.tur-kir.dix)

**Comment by ftyers** [comment]
- [ ] en-ca and eng-cat need to be merged.

**Comment by jonorthwash** [comment]
What's the status of this issue?  Should we continue to wait to commit to these repos until the history has been merged/updated ?

**Comment by TinoDidriksen** [comment]
Status is I still haven't had time, but you never needed to wait for this ticket. The waiting was the initial 24 hours for Sushain's wide-scale fix. When I do this ticket, I'll just copy over and rewrite history.

**Comment by jonorthwash** [comment]
When you rewrite history, won't it cause problems for any local clone we have of the repo?

**Comment by TinoDidriksen** [comment]
Absolutely, they'll need to be re-cloned. But that's a small price to pay, and it's a one-time occasion.

**Comment by xavivars** [comment]
For eng-cat, spa-cat and fra-cat, I'm sure it'll be fine.

**Comment by jonorthwash** [comment]
Ah, okay.  Should be fine for tur-kir too.

**Comment by TinoDidriksen** [comment]
@jonorthwash, tur-kir seems fine. It has all 1235 commits that were in svn, going from /incubator/apertium-tr-ky to /trunk/apertium-tr-ky to /staging/apertium-tr-ky to /staging/apertium-tur-kir and finally to /nursery/apertium-tur-kir.

**Comment by TinoDidriksen** [comment]
> en-ca and eng-cat need to be merged.

@ftyers, having looked at the history in depth now, no. Work continued in both folders - this wasn't simply a case of eng-cat being created and then files from en-ca were copied over. Merging their history would result in something nasty.

**Comment by xavivars** [comment]
@TinoDidriksen: for eng-cat it's a pity, as most of the work @marcriera did on last GSoC, on top of the new pair, was basically bringing the bidix and rules from the old pair. But probably it had already too much unique history for it to be easy to merge. In that case, it's probably worth to import back the old en-ca to github and archive it there. 

for spa-cat, you can safely discard the few latest commits that were done to the old archived pair. Let me know if you have any question regarding those commits

**Comment by TinoDidriksen** [comment]
@xavivars, I can cherry-pick which revisions get merged from each "branch". It just looked to be very messy and lots of parallel work at first glance. I'll give it another look to see if there is a range of revisions where it makes sense to splice.

The splice process is now sort of documented at:
https://github.com/apertium/apertium-on-github/blob/master/s2g.md

**Comment by TinoDidriksen** [comment]
I think that's done.

I don't know why spa-ita was on the list as it seems complete, and tur-kir is also complete. I guess some files were copied in from other places, but such histories can't be merged - only whole folders can be spliced together.

**Comment by jonorthwash** [comment]
For tur-kir, follow specifically the dix file's [log on svn](https://sourceforge.net/p/apertium/svn/48431/log/?path=/nursery/apertium-tur-kir/apertium-tur-kir.tur-kir.dix) and [on github](https://github.com/apertium/apertium-tur-kir/commits/master?after=18aca089890428c84c8370634a8999a3489f404e+139&path%5B%5D=apertium-tur-kir.tur-kir.dix).  The former goes back much further than the latter.

Its history on github only goes [back to](https://github.com/apertium/apertium-tur-kir/commit/6f3b190ec468a8697c313673702c60126b3ef2b4#diff-fd79dc5cf0affd734202b75ed0f4bc0c) the equivalent of svn [r38021](https://sourceforge.net/p/apertium/svn/38021), but svn tracks it back to [r29255](https://sourceforge.net/p/apertium/svn/29255/).

**Comment by jonorthwash** [comment]
Discussed this via IRC.  Summary is that github has the log for the dix file under its previous name.  Which I'm not sure how to find.

**Comment by sushain97** [comment]
Were there too many changes for Git to pick up the rename?

**Comment by TinoDidriksen** [comment]
@jonorthwash `git log --follow apertium-tur-kir.tur-kir.dix` shows 419 commits for that file, going back to 2011-03-29.

Without --follow it only shows 141, going back to 2012-04-29.

**Comment by jonorthwash** [comment]
> `git log --follow`

Aha, perfect, thanks!

**Comment by jonorthwash** [comment]
Now to s/ipasov/gantu/ in the logs...
