### ISSUE TITLE
Bot account for syncs

### ISSUE THREAD

**Issue by TinoDidriksen** [sushain97/apertium-on-github#37]
We should create an ApertiumBot or similar account that scripts can run as, so that we can share the access to core devs.

**Comment by TinoDidriksen** [comment]
I have created https://github.com/ApertiumBot for these purposes.

**Comment by sushain97** [comment]
To finish this we need to switch out my ssh key in apertium@projectjj with ApertiumBot's. Will you take care of it or shall I? If you'd like me to, I need ApertiumBot's GitHub PW.
