### ISSUE TITLE
Meta-repositories use SSH submodules

### ISSUE THREAD

**Issue by TinoDidriksen** [sushain97/apertium-on-github#39]
The meta-repositories use SSH URLs for submodules, which means anonymous users can't clone them. Need to replace all instances of `git@github.com:apertium/` with `https://github.com/apertium/` for all submodules.

**Comment by sushain97** [comment]
Hmm... wouldn't this make it annoying if you actually worked out of a meta repository? Not sure I would call this a bug. Seems to be a decision of who to annoy (anon users or devs who should be using SSH auth anyway and won't have any trouble).

**Comment by TinoDidriksen** [comment]
That is a good point. Hm. Does anyone work from meta-repos? I guess forget this for now. Just something to be aware of when telling new people what to clone.
