### ISSUE TITLE
Meta-repo track HEAD of master

### ISSUE THREAD

**Issue by TinoDidriksen** [sushain97/apertium-on-github#40]
Instead of constantly syncing submodules via hooks, we can just track the master branch and it will automatically always be the latest. And apparently this has been possible for 5 years.

- https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.2.txt#L186
- https://stackoverflow.com/a/9189815/145919

**Comment by sushain97** [comment]
We already do this: https://github.com/apertium/apertium-on-github/blob/master/sync.py#L196. I don't think it's sufficient though to make the adjustments on the GitHub UI end? Otherwise, all these commits would be blank: https://github.com/apertium/apertium-all/commits/master.

**Comment by sushain97** [comment]
From the conversation on your SO link:

> VonC So to further clarify, the "following a branch" feature only affects the behavior of the git submodule update command by telling it which commit (i.e. the most recent commit on master) to update the submodule to, not automagically cause the parent repo to update which commit is pointed to by the submodule at clone time? – DC_ Jul 26 '17 at 20:22
> DC_ Yes: whenever a submodule change, the parent still has to record that new state (gitlink) from the submodule. – VonC Jul 26 '17 at 20:23

This seems to affirm my understanding of why the sync is necessary (but still kind of stupid).

edit: https://stackoverflow.com/a/18797720 has an even better explanation.

**Comment by TinoDidriksen** [comment]
Erk, you're right...and here I thought it was just some feature they had forgotten to advertise because it's against the git way.
