### ISSUE TITLE
Better metarepo READMEs

### ISSUE THREAD

**Issue by sushain97** [sushain97/apertium-on-github#41]
with useful submodule commands and wiki link

**Comment by shardulc** [comment]
Should I make pull requests to each metarepo, or can we discuss the text here and then commit with @ApertiumBot's account?

**Comment by sushain97** [comment]
There are only 4 so go ahead with PRs. Don't need to involve the bot.

**Comment by shardulc** [comment]
PRs to each meta-repo fixed this yesterday.
