### ISSUE TITLE
transfer apertium-quality to github

### ISSUE THREAD

**Issue by jonorthwash** [sushain97/apertium-on-github#43]
Apertium-quality should be transferred from svn to github (tools repo).

The [wiki page](http://wiki.apertium.org/wiki/Apertium-quality/Installation) will also need to be updated.

**Comment by sushain97** [comment]
note to self:
```
./import-repo.sh trunk/apertium-tools/apertium-quality apertium-quality '["apertium-tools"]'
```
should suffice
