### ISSUE TITLE
migrate apertium-wiktionary-tools

### ISSUE THREAD

**Issue by jonorthwash** [sushain97/apertium-on-github#52]
Migrate `apertium-wiktionary-tools` from https://sourceforge.net/p/apertium/svn/HEAD/tree/trunk/apertium-tools/wiktionary/ .

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-wiktionary-tools

**Comment by jonorthwash** [comment]
Thanks for migrating all these over!
